import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "./provider";
import Footer from "@/components/footer/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Astron",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          {children}
          <Footer/>
        </Providers>
      </body>
    </html>
  );
}
